1. Create a Pandas DataFrame from a dictionary of lists.

In [2]:
import pandas as pd
import numpy as np

In [20]:
data = {
    "Name": ["Ram", "Hari", "Sita"],
    "Age": [23, np.nan, 25],
    "Department": ["IT", "HR", "IT"]
}

df = pd.DataFrame(data)
df

   Name   Age Department
0   Ram  23.0         IT
1  Hari   NaN         HR
2  Sita  25.0         IT

2. Read a CSV file into a DataFrame and display the first 5 rows.

In [8]:
csv = pd.read_csv("Salary_Data.csv")
print(csv.head())

    Age  Gender Education Level          Job Title  Years of Experience  \
0  32.0    Male      Bachelor's  Software Engineer                  5.0
1  28.0  Female        Master's       Data Analyst                  3.0
2  45.0    Male             PhD     Senior Manager                 15.0
3  36.0  Female      Bachelor's    Sales Associate                  7.0
4  52.0    Male        Master's           Director                 20.0

     Salary
0   90000.0
1   65000.0
2  150000.0
3   60000.0
4  200000.0

3. Get the number of rows and columns of a DataFrame

In [9]:
print(csv.shape)

(6704, 6)

4. Display all column names and their data types

In [10]:
csv.dtypes

Age                    float64
Gender                  object
Education Level         object
Job Title               object
Years of Experience    float64
Salary                 float64
dtype: object

5. Select a single column and multiple columns

In [21]:
print(df["Name"])
print(df[["Name", "Age"]])

0     Ram
1    Hari
2    Sita
Name: Name, dtype: object
   Name   Age
0   Ram  23.0
1  Hari   NaN
2  Sita  25.0

In [15]:
print(csv["Age"])
print(csv[["Age", "Gender"]])

0       32.0
1       28.0
2       45.0
3       36.0
4       52.0
        ...
6699    49.0
6700    32.0
6701    30.0
6702    46.0
6703    26.0
Name: Age, Length: 6704, dtype: float64
       Age  Gender
0     32.0    Male
1     28.0  Female
2     45.0    Male
3     36.0  Female
4     52.0    Male
...    ...     ...
6699  49.0  Female
6700  32.0    Male
6701  30.0  Female
6702  46.0    Male
6703  26.0  Female

[6704 rows x 2 columns]

6. Select the first 3 rows using iloc

In [16]:
csv.iloc[:3]

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0

7. Find missing values in a DataFrame

In [19]:
csv.isnull()

        Age  Gender  Education Level  Job Title  Years of Experience  Salary
0     False   False            False      False                False   False
1     False   False            False      False                False   False
2     False   False            False      False                False   False
3     False   False            False      False                False   False
4     False   False            False      False                False   False
...     ...     ...              ...        ...                  ...     ...
6699  False   False            False      False                False   False
6700  False   False            False      False                False   False
6701  False   False            False      False                False   False
6702  False   False            False      False                False   False
6703  False   False            False      False                False   False

[6704 rows x 6 columns]

8. Replace all NaN values with "Unknown"

In [23]:
csv_filled = csv.fillna("Unknoown")
csv_filled

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0
6703,26.0,Female,High School,Sales Executive,1.0,35000.0

In [24]:
df_filled = df.fillna("Unknown")
print(df_filled)

   Name      Age Department
0   Ram     23.0         IT
1  Hari  Unknown         HR
2  Sita     25.0         IT

9. Sort the DataFrame by the 'Age' column in descending order

In [25]:
csv_sorted = csv.sort_values(by="Age", ascending=False)
csv_sorted

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
1305,62.0,Male,PhD,Software Engineer Manager,19.0,200000.0
1304,62.0,Male,PhD,Software Engineer Manager,20.0,200000.0
1258,62.0,Male,PhD,Software Engineer Manager,19.0,200000.0
1225,62.0,Male,PhD,Software Engineer Manager,19.0,200000.0
1236,62.0,Male,PhD,Software Engineer Manager,20.0,200000.0
...,...,...,...,...,...,...
5044,21.0,Female,High School,Junior Sales Representative,0.0,25000.0
4897,21.0,Female,High School,Junior Sales Representative,0.0,25000.0
4962,21.0,Female,High School,Junior Sales Representative,0.0,25000.0
172,NaN,NaN,NaN,NaN,NaN,NaN
260,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df_sorted = df.sort_values(by="Age", ascending=False)
print(df_sorted)

   Name   Age Department
2  Sita  25.0         IT
0   Ram  23.0         IT
1  Hari   NaN         HR

10. Group the DataFrame by 'Department' and calculate average salary

In [ ]:
# in my case i used job title
avg_salary = csv.groupby("Job Title")["Salary"].mean()
avg_salary

Job Title
Account Manager              75000.000000
Accountant                   55000.000000
Administrative Assistant     50000.000000
Back end Developer          102352.561475
Business Analyst             77500.000000
                                ...
UX Designer                  80000.000000
UX Researcher                65000.000000
VP of Finance               200000.000000
VP of Operations            190000.000000
Web Developer                66436.781609
Name: Salary, Length: 193, dtype: float64