Write a Python program using Pandas to create a table that contains the following columns and data:

Employee Name: John, Kate, Leo

Department: IT, HR, Sales

Salary: 50000, 55000, 60000

In [1]:
import pandas as pd

In [3]:
data ={
    "Employee Name": ["John", "Kate", "Leo"],
    "Department": ["IT", "HR", "Sales"],
    "Salary": [50000, 55000, 60000]
}

df = pd.DataFrame(data)
df

  Employee Name Department  Salary
0          John         IT   50000
1          Kate         HR   55000
2           Leo      Sales   60000

Using a list of lists, create a Pandas DataFrame for the following data and set the column name as "Employee", "Department", "Salary"

In [4]:
data = [
    ["John", "IT", 50000],
    ["Kate", "HR", 55000],
    ["Leo", "Sales", 60000]
]

df = pd.DataFrame(data, columns=["Employee", "Department","Salary"])
df

  Employee Department  Salary
0     John         IT   50000
1     Kate         HR   55000
2      Leo      Sales   60000